INSERT INTO `africanmixedcouture`.`creation` (`idcategorie`, `id_creation`, `libelle`, `description`, `prix`, `urlachat`, `genre`, `dateAjout`) VALUES ('4', NULL, 'Combinaison short style Sixties à col cravatte bicolore et bi-matière en tissus Africain', 'Même modèle que la combi-short "Pure White", chic et décontractée, réalisée en velours frappé jaune citron et en tissus Africain, Ankara 100% coton, en provenance direct du Nigeria, jaune citron à motifs géométriques marron chocolat.
Col cravatte à nouer dans le dos, emmanchures Américaines et ouverture forme goutte sur la poitrine.
Haut entièrement doublé en Acetate jaune.
Fermeture dos à glissière.
2 poches côté bien profondes
Taille 42
Modèle réalisable dans d''autres tissus Africains rapportés du Nigeria par mes soins et dans plusieurs tailles sur simple commande 
REMARQUE : Sur la photo où la combi-short est portée et réalisée en tissus blanc uni, il s''agit exactement du même modèle et de la même taille, mais avec d''autres tissus.', '90', 'http://www.alittlemarket.com/autres-mode/fr_combinaison_short_style_sixties_bicolore_et_bi_matiere_en_tissus_africain_-14913409.html', 'féminin', '2015-12-15');